### ISSUE TITLE
建议增加手动上传命令，并非要build之类的其他操作

### ISSUE THREAD

**Issue by limingziqiang** [woshilaoge/webpack-scp-upload-plugin#1]
有的情况是 我只想上传指定配置的文件到服务器，无需build之后

**Comment by woshilaoge** [comment]
ok 文档已更新，目前版本已支持

关注下个版本，后续支持类似
webpack-scp-upload-plugin --path /home/demo --psd 192.123.23.23@**** --local dist

**Comment by woshilaoge** [comment]
https://github.com/woshilaoge/webpack-scp-upload-plugin#npm-bin-%E8%BF%90%E8%A1%8C 已添加，明哥 @limingziqiang
